# -*- coding: utf-8 -*-
"""RESPUESTA_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gePTvDz3Kmbzl1jgepaY3MXrUDgdQDl5
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Cargar el dataset
file_path = '/content/drive/MyDrive/datos/diabetes_data.csv'
dataset = pd.read_csv(file_path)

# Mostrar las primeras filas del dataset
print(dataset.head())

# Normalización: (x - media) / desviación estándar
normalized_dataset = (dataset - dataset.mean()) / dataset.std()

# Mostrar las primeras filas del dataset normalizado
print(normalized_dataset.head())

def l1_penalty(weights, lambda_value):
    """Calcula la penalización L1."""
    return lambda_value * sum(abs(w) for w in weights)

def l2_penalty(weights, lambda_value):
    """Calcula la penalización L2."""
    return lambda_value * sum(w**2 for w in weights)

# Coeficientes de ejemplo
example_weights = [0.5, -1.2, 0.3, 0.7, -0.8]  # Ajusta esto según tus necesidades

# Valor de lambda
lambda_value = 0.1

# Calcular penalización L1 y L2
l1 = l1_penalty(example_weights, lambda_value)
l2 = l2_penalty(example_weights, lambda_value)

print(f'Penalización L1: {l1}')
print(f'Penalización L2: {l2}')